config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :confirmations => "confirmations",
                                       :passwords => "passwords",
                                       :sessions => "sessions" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: [:index, :show]
  resources :posts, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:index]
  resources :messages, only: [:create]
  resources :phonecalls, only: [:create]
  resources :favorites, only: [:create, :destroy]

  resources :users, except: [:destroy, :index] do
    member do
      get :favorites
      patch :set_password
      delete :destroy_social_account
    end
  end

  controller :cart do
    get   '/cart',                 action: :show,     as: :cart
    get   '/cart/disabled',        action: :disabled, as: :disabled_cart
    post  '/cart/add/:product_id', action: :add,      as: :add_in_cart

    patch '/cart', constraints: -> (r) { r.params[:update].present? },   action: :update
    patch '/cart', constraints: -> (r) { r.params[:checkout].present? }, action: :checkout
  end

  controller :static do
    get 'contacts', as: :contacts
    get 'feedbacks', as: :feedbacks
    get 'about', as: :about
  end

  get '404', :to => 'errors#page_not_found'
  get '500', :to => 'errors#server_error'

  controller :payments do
    post 'notify', as: :notify
  end

  post '/liqpay_payment' => 'payments#liqpay_payment'

  root 'home#index'

end

app/views/shared/_categories.slim
nav#catalog-menu.catalog
  .panel.list-group
    = link_to products_path, class: "list-group-item active" do
      i.ion-ios-list-outline
      | Каталог
      span.badge
        = @product_count

    - @home_categories.each do |category|
      = link_to category, class: "list-group-item" do
        = category.title
        span.badge
          = category.products.count

app/views/shared/_faq.slim
.widget-block
  #accordion.panel-group
    - @faq.each_with_index do |question, i|
      .panel.panel-default
        .panel-heading
          h4.panel-title
            a.collapsed data-parent="#accordion" data-toggle="collapse" href="#collapse_#{i}"
              = question.title
        .panel-collapse.collapse id="collapse_#{i}"
          .panel-body
            = question.answer

app/views/shared/_flash_messages.slim
.alert.alert-success.alert-dismissable style="display:none" id="favorites-success"
  button.close data-dismiss="alert" aria-hidden="true" &times;
  | Продукт добавлен в избранное.


.alert.alert-warning.alert-dismissable style="display:none" id="favorites-success-remove"
  button.close data-dismiss="alert" aria-hidden="true" &times;
  | Продукт удален из избранного.


.alert.alert-success.alert-dismissable style="display:none" id="settings-success"
  button.close data-dismiss="alert" aria-hidden="true" &times;
  | Изменения сохранены

.alert.alert-warning.alert-dismissable style="display:none" id="settings-error"
  .button.close data-dismiss="alert" aria-hidden="true" &times;
  |Ошибка сохранения. Проверьте правильность ввода данных

app/views/shared/_login.slim
#login.modal.fade aria-hidden="true" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h3 PrettyPeople
      .modal-body
        .block-product-detail
          .row
            section
              .block2
                .col-md-6.col-sm-8.col-md-offset-3.col-sm-offset-2
                  .block-form.box-border.wow.fadeInLeft.animated data-wow-duration="1s"
                    h3
                      i.fa.fa-unlock
                      | Вход
                    = form_tag user_session_path, remote: true
                      .row
                        .col-md-6
                          = text_field_tag "user[email]", "", class: "form-control", placeholder: "Email"
                        .col-md-6
                          = password_field_tag "user[password]", "", class: "form-control", placeholder: "Пароль"
                        .col-md-12
                          = submit_tag "Войти", class: "btn-default"
                          |&nbsp;
                          |&nbsp;
                          a.read-more style="cursor:pointer" id="reset_password_button_alt" Забыли пароль?
                    hr
                    p Войти с помощью
                    = link_to "<i class='flaticon-vk'></i> &nbsp;&nbsp;Вконтакте".html_safe, user_omniauth_authorize_path(:vkontakte), class: "btn-default"
                    =< link_to "<i class='fa fa-facebook'></i> &nbsp;&nbsp;Facebook".html_safe, user_omniauth_authorize_path(:facebook), class: "btn-default"
                    hr

app/views/shared/_login_alt.slim
#login_alt.modal.fade aria-hidden="true" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h3 PrettyPeople
      .modal-body
        .block-product-detail
          .row
            section
              .block2
                .col-md-6.col-sm-8.col-md-offset-3.col-sm-offset-2
                  .block-form.box-border.wow.fadeInLeft.animated data-wow-duration="1s"
                    h3
                      i.fa.fa-unlock
                      | Войдите или зарегистрируйтесь
                    = form_tag user_session_path, remote: true
                      .row
                        .col-md-6
                          = text_field_tag "user[email]", "", class: "form-control", placeholder: "Email"
                        .col-md-6
                          = password_field_tag "user[password]", "", class: "form-control", placeholder: "Пароль"
                        .col-md-12
                          = submit_tag "Войти", class: "btn-default"
                          |&nbsp;
                          |&nbsp;
                          a.read-more style="cursor:pointer" id="reset_password_button" Забыли пароль?
                    hr
                    p Войти с помощью
                    = link_to "<i class='flaticon-vk'></i> &nbsp;&nbsp;Вконтакте".html_safe, user_omniauth_authorize_path(:vkontakte), class: "btn-default"
                    =< link_to "<i class='fa fa-facebook'></i> &nbsp;&nbsp;Facebook".html_safe, user_omniauth_authorize_path(:facebook), class: "btn-default"
                    hr
                    p Нет аккаунта?
                    a.btn-default id="registernow" style="cursor:pointer"
                      |Зарегистрируйтесь

#reset_password.modal.fade aria-hidden="true" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h3 PrettyPeople
      .modal-body
        .block-product-detail
          .row
            section
              .block2
                .col-md-6.col-sm-8.col-md-offset-3.col-sm-offset-2
                  .block-form.box-border.wow.fadeInLeft.animated data-wow-duration="1s"
                    h3
                      i.fa.fa-unlock
                      | Сброс пароля
                    = form_tag user_password_path, remote: true do
                      .row
                        .col-md-6
                          = text_field_tag "user[email]", "", class: "form-control", placeholder: "Email"
                        .col-md-12
                          = submit_tag "Отправить", class: "btn-default"

                    hr
                    p На указанный email будет выслана инструкция по сбросу пароля

app/views/shared/_new_password.slim
- if params[:user] && params[:set_password] == "true"
  - if User.find(params[:user]).confirmed? && User.find(params[:user]).password.blank?
    - user = User.find(params[:user])
    #new_password.modal.fade.in aria-hidden="false" role="dialog" tabindex="-1" style="display:block"
      .modal-dialog
        .modal-content
          .modal-header
            button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
            h3 PrettyPeople
          .modal-body
            .block-product-detail
              .row
                section
                  .block2
                    .col-md-6.col-sm-8.col-md-offset-3.col-sm-offset-2
                      .block-form.box-border.wow.fadeInLeft.animated data-wow-duration="1s"
                        h3
                          i.fa.fa-unlock
                          | Создание пароля
                        #error_messages style="display:none"
                          h5 style="color:#d05165"
                            | Ошибка. Проверьте правильность ввода.
                            br
                            | Пароль должен быть не меньше 8 символов.
                        hr
                        = form_for user, :remote => true, :url => set_password_user_path(User.find(params[:user])) do |f|
                          .row
                            .col-md-12
                              = f.text_field :name, class: "form-control", placeholder: "Ваше имя"
                            hr
                            .col-md-12
                              = f.password_field :password, class: "form-control", placeholder: "Введите пароль (не меньше 8 символов)", :autocomplete => :off
                            .col-md-12
                              = f.password_field :password_confirmation, class: "form-control", placeholder: "Повторите пароль"
                            .col-md-12
                              = submit_tag "Войти", class: "btn-default"
    .modal-backdrop.fade.in

- if params[:reset_password_token]
  - if @user
    #new_password_reset.modal.fade.in aria-hidden="false" role="dialog" tabindex="-1" style="display:block"
      .modal-dialog
        .modal-content
          .modal-header
            button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
            h3 PrettyPeople
          .modal-body
            .block-product-detail
              .row
                section
                  .block2
                    .col-md-6.col-sm-8.col-md-offset-3.col-sm-offset-2
                      .block-form.box-border.wow.fadeInLeft.animated data-wow-duration="1s"
                        h3
                          i.fa.fa-unlock
                          | Сброс пароля
                        #error_messages style="display:none"
                          h5 style="color:#d05165"
                            | Ошибка. Проверьте правильность ввода.
                            br
                            | Пароль должен быть не меньше 8 символов.
                        hr
                        = form_for @user, remote: true, url: set_password_user_path(@user) do |f|
                          .row
                            .col-md-12
                              = f.password_field :password, class: "form-control", placeholder: "Введите новый пароль (не меньше 8 символов)", autocomplete: :off
                            hr
                            .col-md-12
                              = f.password_field :password_confirmation, class: "form-control", placeholder: "Введите повторно"
                            .col-md-12
                              = submit_tag "Войти", class: "btn-default"
    .modal-backdrop.fade.in

app/views/shared/_order_status.slim
- if current_user
  #order_status.modal.fade.in aria-hidden="false" role="dialog" tabindex="-1" style="display:block"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
          h3 PrettyPeople
        .modal-body
          .block-product-detail
            .row
              section
                .block2
                  .col-md-6.col-sm-8.col-md-offset-3.col-sm-offset-2
                    .block-form.box-border.wow.fadeInLeft.animated data-wow-duration="1s"
                      h3
                        i.fa.fa-credit-card
                        | Статус заказа
                      p
                        = "Ваш заказ"
                        strong
                          =< "№"
                          = @order.id
                        =< "успешно оформлен!"
                      p
                        |Вы можете оплатить заказ, удобным для Вас способом:
                      = link_to "Оплатить курьеру", root_path, class: "btn-default"
                      = liqpay_button @liqpay_request do
                        = link_to "Оплатить картой", '#', :onclick => "document.getElementById('liqpay_form').submit();", :class => "btn-default"
                      hr
                      p style="font-size:12px"
                        'Оплата картой производится через банковскую систему безопасных платежей
                        a href="https://www.liqpay.com" target="_blank"
                          strong
                            | LiqPay.
                        | &nbsp; Вы не предоставляете третьим лицам персональные данные, банковские реквизиты и номер кредитной или дебитской карты.
  .modal-backdrop.fade.in

app/views/shared/_payment_status.slim
- if current_user
  #order_payment.modal.fade.in aria-hidden="false" role="dialog" tabindex="-1" style="display:block"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
          h3 PrettyPeople
        .modal-body
          .block-product-detail
            .row
              section
                .block2
                  .col-md-6.col-sm-8.col-md-offset-3.col-sm-offset-2
                    .block-form.box-border.wow.fadeInLeft.animated data-wow-duration="1s"
                      h3
                        i.fa.fa-credit-card
                        | Оплата заказа
                      p
                        = "Мы получили оплату за заказ"
                        strong
                          =< "№"
                          = @order.id
                        =<"и скоро свяжемся с Вами для уточнения деталей."
                      p
                      = link_to "Ок", root_path, class: "btn-default"

                      hr
  .modal-backdrop.fade.in

app/views/shared/_phonecall.slim
#phonecall_modal.modal.fade.in aria-hidden="false" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h3 PrettyPeople
      .modal-body
        .block-product-detail
          .row
            section
              .block2
                .col-md-6.col-sm-8.col-md-offset-3.col-sm-offset-2
                  .block-form.box-border.wow.fadeInLeft.animated data-wow-duration="1s"
                    h3
                      i.fa.fa-phone
                      | Обратный звонок
                    #error_messages style="display:none"
                      h5 style="color:#d05165"
                        | Ошибка. Проверьте правильность ввода.
                    hr
                    = form_for Phonecall.new, html: { id: "phonecall_form", :remote => true } do |f|
                      .row
                        .col-md-12
                          = f.text_field :phone, class: "form-control", placeholder: "Ваш номер телефона"
                        hr

                        .col-md-12
                          = submit_tag "Отправить", class: "btn-default"
.modal-backdrop.fade.in

app/views/shared/_promo_post.slim
- unless @promo_post.blank?
  section
    .block-blog.item1 style="background-image: url('#{image_path @promo_post.image}')"
      .blog-item-container.block
        .container
          .row
            .col-md-6.col-sm-6
            .col-md-6.col-sm-6
              article.blog-item
                .product-title
                  = @promo_post.title
                p
                  = @promo_post.description
                = link_to "Подробнее", @promo_post, class: "read-more"
                .blog-item-date
                  p.month style="font-size:12px !important"
                    =l @promo_post.created_at.to_date, format: :month_only
                  p.day
                    =l @promo_post.created_at.to_date, format: :date_only

app/views/shared/_promo_product.slim
.row
  article.product
    figure.figure-hover-overlay
      = link_to @promo_product, class: "figure-href" do
      - unless @promo_product.badge.blank?
        .product-new
          = @promo_product.badge

      - unless @promo_product.discount_badge.blank?
        .product-sale
          = @promo_product.discount_badge

      - if current_user
        - if Favorite.find_by(:user => current_user, :product => @promo_product).blank?
          = link_to favorites_path(:product_id => @promo_product.id), :method => "POST", remote: true, class: "product-compare", title: "В избранное"
            i.ion-ios-heart-outline
        - else
          = link_to Favorite.find_by(:user => current_user, :product => @promo_product), method: "DELETE", remote: true, class: "product-compare favorite", title: "Удалить из избранного"
            i.ion-ios-heart-outline

      - if current_user
        = link_to add_in_cart_path(@promo_product.id), method: :post, remote: true, class: 'product-cart', title: "В корзину" do
          i.ion-ios-cart-outline
      - else
        a href="" class="product-cart" data-toggle="modal" data-target="#login_alt"
          i.ion-ios-cart-outline

      = link_to @promo_product, class: "quick-view" do
        i.ion-ios-eye-outline

      = image_tag @promo_product.image.url(:home), class: "img-responsive", alt: "#{@promo_product.title}"
    .product-caption
      .product-sale-time.clearfix
        p.time id="time-data" data-cdate="#{@promo_product.promo_date.strftime('%B %d, %Y %H:%M:00')}"
      .block-name
        = link_to @promo_product, class: "product-name" do
          = @promo_product.title
        = @promo_product.category.title unless @promo_product.category.blank?
        p.product-price
          - unless @promo_product.old_price.blank?
            span
              = price_format @promo_product.old_price
              =< "грн."
            |&nbsp;
          = price_format @promo_product.price
          =< "грн."

app/views/shared/_random_category.slim
.banner-collection
  = link_to @random_category do
  .banner-title
    span
      = @random_category.title
    | смотреть все
  = image_tag @random_category.image.url, class: "img-responsive"

app/views/shared/_registration.slim
#registration.modal.fade aria-hidden="true" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h3 PrettyPeople
      .modal-body
        .block-product-detail
          .row
            section
              .block2
                .col-md-6.col-sm-8.col-md-offset-3.col-sm-offset-2
                  .block-form.box-border.wow.fadeInLeft.animated data-wow-duration="1s"
                    h3
                      i.fa.fa-unlock
                      | Новый аккаунт
                    #error_creation_messages style="display:none"
                      h5 style="color:#d05165"
                        | Ошибка. Проверьте правильность ввода.
                        br
                        | Возможно такой email уже зарегистрирован в системе.
                    p Создать новый аккаунт с помощью

                    = link_to "<i class='flaticon-vk'></i> &nbsp;&nbsp;Вконтакте".html_safe, user_omniauth_authorize_path(:vkontakte), :class => "btn-default"
                    =< link_to "<i class='fa fa-facebook'></i> &nbsp;&nbsp;Facebook".html_safe, user_omniauth_authorize_path(:facebook), :class => "btn-default"

                    hr
                    p Регистрация через e-mail
                    = form_for User.new, :html => {:autocomplete => "off"}, :remote => true do |f|
                      .row
                        .col-md-12
                          = f.text_field :email, class: "form-control", placeholder: "E-mail"
                        .col-md-12
                          = f.submit "Зарегистрироваться", class: "btn-default"

app/views/shared/_sendmail.slim
#send_mail.modal.fade aria-hidden="true" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h3 PrettyPeople
      .modal-body
        .block-product-detail
          .row
            section
              .block2
                .col-md-6.col-sm-8.col-md-offset-3.col-sm-offset-2
                  .block-form.box-border.wow.fadeInLeft.animated data-wow-duration="1s"
                    h3
                      i.fa.fa-unlock
                      | Активация
                    p
                      |Мы отправили письмо с инструкциями на указанный электронный адрес.
                    = link_to "Ок", root_path, class: "btn-default"
                    hr

#send_mail_reset.modal.fade aria-hidden="true" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h3 PrettyPeople
      .modal-body
        .block-product-detail
          .row
            section
              .block2
                .col-md-6.col-sm-8.col-md-offset-3.col-sm-offset-2
                  .block-form.box-border.wow.fadeInLeft.animated data-wow-duration="1s"
                    h3
                      i.fa.fa-unlock
                      | Сброс пароля
                    p
                      |Мы отправили письмо с инструкциями по сбросу пароля на указанный электронный адрес.
                    = link_to "Ок", root_path, class: "btn-default"
                    hr