config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :confirmations => "confirmations",
                                       :passwords => "passwords",
                                       :sessions => "sessions" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: [:index, :show]
  resources :posts, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:index]
  resources :messages, only: [:create]
  resources :phonecalls, only: [:create]
  resources :favorites, only: [:create, :destroy]

  resources :users, except: [:destroy, :index] do
    member do
      get :favorites
      patch :set_password
      delete :destroy_social_account
    end
  end

  controller :cart do
    get   '/cart',                 action: :show,     as: :cart
    get   '/cart/disabled',        action: :disabled, as: :disabled_cart
    post  '/cart/add/:product_id', action: :add,      as: :add_in_cart

    patch '/cart', constraints: -> (r) { r.params[:update].present? },   action: :update
    patch '/cart', constraints: -> (r) { r.params[:checkout].present? }, action: :checkout
  end

  controller :static do
    get 'contacts', as: :contacts
    get 'feedbacks', as: :feedbacks
    get 'about', as: :about
  end

  get '404', :to => 'errors#page_not_found'
  get '500', :to => 'errors#server_error'

  controller :payments do
    post 'notify', as: :notify
  end

  post '/liqpay_payment' => 'payments#liqpay_payment'

  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  before_save :check_seo

  extend FriendlyId
  friendly_id :title, use: :slugged
  validates :title, :presence => true

  default_scope -> { order('created_at DESC') }

  scope :published, -> { where('published = ?', true) }
  scope :promo, -> { where('published = ? AND promo = ?', true, true) }

  has_attached_file :image, styles: {  thumb: "90x80#", index: "900x800", original: "1680x1050#" }, default_style: :original

  validates_attachment :image,
    content_type: { content_type: /^image\/(jpeg|jpg|png|gif)$/ },
    size: { in: 0..5.megabytes }

  def check_seo
    if self.seo_title.blank?
      self.seo_title = self.title
    end

    if self.seo_description.blank?
      self.seo_description = self.description unless self.description.blank?
    end
  end

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.published.all

    @page = Page.find_by(:title => "posts")
    set_seo(@page)
  end

  def show
    @post = Post.friendly.find(params[:id])
    @other_posts = Post.where('id != ?', @post.id).limit(3)
    set_seo(@post)
  end

end

app/views/posts/index.slim
section
  .top-header-bg.light
  .second-page-header.bg-light
    .container
      .row
        .col-md-12
          h1 Новости
          ul.breadcrumb
            li
              = link_to "Главная", root_path
            li
            li.active Новости

section
  .home-block
    .container
      .row
        .col-md-9.col-sm-8
          - @posts.each_slice(2) do |slice|
            .row
              - slice.each do |post|
                .col-md-6
                  .post-blog
                    .post-blog-img
                      .post-date
                        span.day
                          =l post.created_at.to_date, format: :date_only
                        span.month
                          =l post.created_at.to_date, format: :month_only
                      = link_to post
                        = image_tag post.image.url(:index), class: "img-responsive", alt: "#{post.title}"
                    = link_to post.title, post, class: "post-title"
                    p
                      = post.description
                    = link_to "Читать", post, class: "btn-default"

        .col-md-3.col-sm-4
          - unless @random_category.blank?
            = render 'shared/random_category'
          - unless @promo_product.blank?
            = render 'shared/promo_product'


= render "shared/promo_post"

app/views/posts/show.slim
section
  .top-header-bg.light
  .second-page-header.bg-light
    .container
      .row
        .col-md-12
          .post-title
            = @post.title
          ul.breadcrumb
            li
              = link_to "Главная", root_path
            li
              = link_to "Новости", posts_path
            li.active
              = truncate @post.title, length: 20
section
  .home-block
    .container
      .row
        .col-md-9.col-sm-8
          .block-blog
            = image_tag @post.image.url, class: "img-responsive br3", alt: "#{@post.title}"

            br
            .article-body
              = @post.text.try(:html_safe)

            - unless @other_posts.blank?
              .block2
                .header-for-light
                  .titelize Другие новости
              .row
                - @other_posts.each do |post|
                  .col-md-4
                    .post-blog
                      .post-blog-img
                        .post-date
                          span.day
                            =l post.created_at.to_date, format: :date_only
                          span.month
                            =l post.created_at.to_date, format: :month_only
                        = link_to post
                          = image_tag post.image.url(:index), class: "img-responsive", alt: "#{post.title}"
                      = link_to post.title, post, class: "post-title"
                      p
                        = post.description
                      = link_to "Читать", post, class: "btn-default"

        .col-md-3.col-sm-4
          = render "shared/categories"

          - unless @random_category.blank?
            = render 'shared/random_category'
          - unless @promo_product.blank?
            = render 'shared/promo_product'
          - unless @faq.blank?
            = render 'shared/faq'


= render "shared/promo_post"