config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :confirmations => "confirmations",
                                       :passwords => "passwords",
                                       :sessions => "sessions" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :products, only: [:index, :show]
  resources :posts, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :orders, only: [:index]
  resources :messages, only: [:create]
  resources :phonecalls, only: [:create]
  resources :favorites, only: [:create, :destroy]

  resources :users, except: [:destroy, :index] do
    member do
      get :favorites
      patch :set_password
      delete :destroy_social_account
    end
  end

  controller :cart do
    get   '/cart',                 action: :show,     as: :cart
    get   '/cart/disabled',        action: :disabled, as: :disabled_cart
    post  '/cart/add/:product_id', action: :add,      as: :add_in_cart

    patch '/cart', constraints: -> (r) { r.params[:update].present? },   action: :update
    patch '/cart', constraints: -> (r) { r.params[:checkout].present? }, action: :checkout
  end

  controller :static do
    get 'contacts', as: :contacts
    get 'feedbacks', as: :feedbacks
    get 'about', as: :about
  end

  get '404', :to => 'errors#page_not_found'
  get '500', :to => 'errors#server_error'

  controller :payments do
    post 'notify', as: :notify
  end

  post '/liqpay_payment' => 'payments#liqpay_payment'

  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  before_save :check_seo

  extend FriendlyId
  friendly_id :title, use: :slugged
  validates :title, :presence => true

  has_many :products, dependent: :destroy

  has_attached_file :image, styles: { thumb: '100x', admin_show: '350x', index: '753x304#', original: '900x1200#'}, default_style: :original
  validates_attachment :image,
    content_type: { content_type: /^image\/(jpeg|jpg|png|gif)$/ },
    size: { in: 0..5.megabytes }

  scope :published, -> { where('published = ?', true) }
  default_scope -> { order('position DESC') }

  def check_seo
    if self.seo_title.blank?
      self.seo_title = self.title
    end

    if self.seo_description.blank?
      self.seo_description = self.description unless self.description.blank?
    end
  end

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.published.all

    @page = Page.find_by(:title => "categories")
    set_seo(@page)
  end

  def show
    @category = Category.friendly.find(params[:id])
    set_seo(@category)
  end

end

app/views/categories/index.slim
section
  .top-header-m-bg.light
  .second-page-header.bg-light
    .container
      .row
        .col-md-12
          h1 Каталог
          ul.breadcrumb
            li
              = link_to "Главная", root_path
            li.active Каталог

  .block2
    .container
      .header-for-light.clearfix
        h2 Категории
        = link_to "Все продукты", products_path, class: "see-all"
      .row
        - @categories.each do |category|
          .col-md-3.col-sm-6
            .banner-collection
              = link_to category do
              .banner-title
                span
                  = category.title
                = truncate category.description, length: 170 unless category.description.blank?
              = image_tag category.image.url, class: "img-responsive", alt:"#{category.title}"

app/views/categories/show.slim
section
  .top-header-m-bg.dark
  .second-page-header.bg-light
    .container
      .row
        .col-md-12
          h1
            = @category.title

          ul.breadcrumb
            li
              = link_to "Главная", root_path
            li
              = link_to "Каталог", categories_path
            li.active
              = @category.title

section
  .home-block
    .container
      .row
        .col-md-9.col-sm-8
          .row
            - @category.products.each do |product|
              .col-md-4.col-sm-6.no-pad
                article.product
                  figure.figure-hover-overlay.rentengle
                    = link_to product, class: "figure-href" do
                    - if product.published != false
                      - unless product.badge.blank?
                        .product-new
                          = product.badge

                      - unless product.discount_badge.blank?
                        .product-sale
                          = product.discount_badge

                    - if current_user
                      - if Favorite.find_by(:user => current_user, :product => product).blank?
                        = link_to favorites_path(:product_id => product.id), :method => "POST", remote: true, class: "product-compare", title: "В избранное"
                          i.ion-ios-heart-outline
                      - else
                        = link_to Favorite.find_by(:user => current_user, :product => product), method: "DELETE", remote: true, class: "product-compare favorite", title: "Удалить из избранного"
                          i.ion-ios-heart-outline

                    - if product.published != false
                      - if current_user
                        = link_to add_in_cart_path(product.id), method: :post, remote: true, class: "product-cart", title: "Добавить в корзину" do
                          i.ion-ios-cart-outline
                      - else
                        a href="" class="product-cart" data-toggle="modal" data-target="#login_alt" title="Добавить в корзину"
                          i.ion-ios-cart-outline

                    = image_tag product.image.url(:home), class: "img-responsive img-overlay", alt: "#{product.title}"
                    = image_tag product.image.url(:home), class: "img-responsive", alt: "#{product.title}"

                  .product-caption
                    .block-name
                      = link_to product, class: "product-name" do
                        = product.title
                      = product.category.title unless product.category.blank?
                      - if product.published != false
                        p.product-price
                          - unless product.old_price.blank?
                            span
                              = price_format product.old_price
                              =< "грн."
                            |&nbsp;
                          = price_format product.price
                          =< "грн."
                      - else
                        p.product-price
                          = "Нет в наличии"
        .col-md-3.col-sm-4
          = render "shared/categories"

= render "shared/promo_post"